version: '3.4'
services:
  acme-share-ui-share:
    image: alfresco-share-acme-share-ui:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: ${acs.host}
      REPO_PORT: ${acs.port}
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
# Optional
#  acme-share-ui-acs:
#    image: ${docker.acs.image}:${alfresco.platform.version}
#    environment:
#      JAVA_OPTS: "
#                -Ddb.driver=org.postgresql.Driver
#                -Ddb.username=alfresco
#                -Ddb.password=alfresco
#                -Ddb.url=jdbc:postgresql://acme-share-ui-postgres:5432/alfresco
#                -Dsolr.host=acme-share-ui-ass
#                -Dsolr.port=8983
#                -Dsolr.secureComms=secret
#                -Dsolr.sharedSecret=secret
#                -Dsolr.base.url=/solr
#                -Dindex.subsystem.name=solr6
#                -Dcsrf.filter.enabled=false
#                -Dmessaging.broker.url=\"vm://localhost?broker.persistent=false\"
#                -Dtransform.service.enabled=false
#                -Dlocal.transform.service.enabled=false
#                -Dlegacy.transform.service.enabled=false
#                ${keystore.settings}
#                "
#    ports:
#      - "${acs.port}:8080"
#    volumes:
#      - acme-share-ui-acs-volume:/usr/local/tomcat/alf_data
#    depends_on:
#      - acme-share-ui-postgres
#  acme-share-ui-postgres:
#    image: postgres:9.6
#    environment:
#      POSTGRES_DB: alfresco
#      POSTGRES_USER: alfresco
#      POSTGRES_PASSWORD: alfresco
#    command: postgres -c max_connections=300 -c log_min_messages=LOG
#    ports:
#      - "${postgres.port}:5432"
#    volumes:
#      - acme-share-ui-db-volume:/var/lib/postgresql/data
#  acme-share-ui-ass:
#    image: alfresco/alfresco-search-services:2.0.3
#    environment:
#      SOLR_ALFRESCO_HOST: acme-share-ui-acs
#      SOLR_ALFRESCO_PORT: 8080
#      SOLR_SOLR_HOST: acme-share-ui-ass
#      SOLR_SOLR_PORT: 8983
#      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
#      ALFRESCO_SECURE_COMMS: "secret"
#      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
#    ports:
#      - "8983:8983"
#    volumes:
#      - acme-share-ui-ass-volume:/opt/alfresco-search-services/contentstore
#      - acme-share-ui-ass-volume:/opt/alfresco-search-services/data
#volumes:
#  acme-share-ui-acs-volume:
#    external: true
#  acme-share-ui-db-volume:
#    external: true
#  acme-share-ui-ass-volume:
#    external: true
